### ISSUE TITLE
Needs Comments

### ISSUE THREAD

**Issue by zhuntai** [zhuntai/BearLight#3]
Please look through and comment the code.

**Comment by baspalinckx** [comment]
I will do some commenting if you would like? Could you assign me and be a little bit more specific?

**Comment by zhuntai** [comment]
Thanks! I've assigned you. The main file in question is the ino file. It's for arduino platform. I've added some basic comments to it so you can get a feel of how it's supposed to run. Make it look uniform and add additional comments as you see fit. Doesn't have to be particularly verbose. Thank you!
